FROM continuumio/miniconda3

RUN apt-get update -y
RUN apt-get upgrade -y

RUN apt-get install build-essential -y

RUN pip install --upgrade pip setuptools wheel

ADD requirements.txt /prereqs/
RUN pip install -r ./prereqs/requirements.txt

COPY . .

ENV SUBSCRIPTION_ID=deb5499f-5958-40c3-bc4e-6045d9bc3e12 \
RESOURCE_GROUP=laah-db-dev \
WORKSPACE_NAME=laah-db-ml-dev \
STATE=dev \
AUTHOR=dev \
MODEL_NAME=" \
IMAGE_NAME="

#Ensures python print lines are printed out
ENV PYTHONUNBUFFERED 1

CMD ["python", "build.py"]
